version: "3.8"

services:
  app:
    image: node:16-alpine
    command: sh -c "npm install && npm start"
    ports:
      - 3001:3001
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      PORT: 3001